import Link from "next/link";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./app.module.css";
import MainNavigation from "@/components/MainNavigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Simple Film Finder",
  description: "Generated by create next app",
  icons: {
    icon: { url: "/favicon.ico" },
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className={styles.container}>
          <MainNavigation />
          {children}
        </main>
      </body>
    </html>
  );
}
